Metrics/AbcSize:
    Max: 42

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'lib/lab_manager/models/compute.rb'
    - 'lib/lab_manager/models/action.rb'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'config/application.rb'
    - 'db/migrate/20150819122640_create_computes.rb'
    - 'db/migrate/20150909130531_create_actions.rb'
    - 'lib/lab_manager/models.rb'
