default: &default
  log_level: <%= Logger::WARN %>
  sentry_dsn:
  graphite:
  providers:
    - v_sphere
    - static_machine
  redis:
    url: redis://localhost:6379
    pool: 3
  scheduler:
    sleep_time: 2

development:
  <<: *default
  log_level: <%= Logger::DEBUG %>


test:
  <<: *default
  log_level: <%= Logger::INFO %>

production:
  <<: *default

